export default {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  rules: {
    'declaration-empty-line-before': null,
    'selector-class-pattern': null,
    'order/order': ['custom-properties', 'declarations'],
    'order/properties-order': [
      [
        {
          emptyLineBefore: 'always',
          properties: [
            'position',
            'inset',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
          ],
        },
        {
          emptyLineBefore: 'always',
          properties: [
            'display',
            'flex',
            'flex-direction',
            'flex-wrap',
            'align-items',
            'align-content',
            'justify-content',
            'justify-items',
            'place-items',
            'grid-template-columns',
            'grid-template-rows',
            'grid-column',
            'grid-row',
            'gap',
          ],
        },
        {
          emptyLineBefore: 'always',
          properties: [
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'padding',
            'box-sizing',
          ],
        },
        {
          emptyLineBefore: 'always',
          properties: [
            'font',
            'font-family',
            'font-size',
            'font-weight',
            'line-height',
            'letter-spacing',
            'text-align',
            'color',
          ],
        },
        {
          emptyLineBefore: 'always',
          properties: [
            'background',
            'background-color',
            'border',
            'border-radius',
            'outline',
            'opacity',
          ],
        },
        {
          emptyLineBefore: 'always',
          properties: [
            'transform',
            'transform-style',
            'perspective',
            'perspective-origin',
            'will-change',
            'transition',
            'transition-property',
            'transition-duration',
            'transition-timing-function',
          ],
        },
        {
          emptyLineBefore: 'always',
          properties: [
            'cursor',
            'pointer-events',
            'touch-action',
            'user-select',
            '-webkit-user-select',
            'contain',
          ],
        },
      ],
      { unspecified: 'bottomAlphabetical' },
    ],
  },
};
